/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CategoriaDAO;
import controller.ProdutoDAO;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Categoria;
import model.Produto;

/**
 *
 * @author ycar2
 */
public class FormCadastrarProduto extends javax.swing.JInternalFrame {
   private String id;
    /**
     * Creates new form FormCadastrarProduto1
     */
    public FormCadastrarProduto() {
         initComponents();
        this.setTitle("Cadastro de Produto");
        this.setResizable(false);
        preencherComboCategoria();
        
    }
    public  FormCadastrarProduto(String id){
        this();
        this.id = id;
        
        //Exibir os dados da Produto selecionada
        Produto obj = new ProdutoDAO().pesquisarPorId(id);
        if (obj != null){
            txtId.setText(Integer.toString(obj.getId()));
            txtNomeProd.setText(obj.getNome());
            txtPreco.setText(Double.toString(obj.getPreco()));
            
            //selecionar a Categoria
            DefaultComboBoxModel m = (DefaultComboBoxModel)cbxCategoria.getModel();
            for (int i = 0; i < m.getSize(); i++) {
                Categoria cat = (Categoria)m.getElementAt(i);
                if ( cat.getId() == obj.getId_categoria() ){
                    cbxCategoria.setSelectedIndex(i);
                    break;
                }
            }
            txtQuantidade1.setText(Integer.toString(obj.getQntd()));
            txtTaxa.setText(Double.toString(obj.getTaxa()));
            cbxAtivo.setSelectedIndex(obj.getFg_ativo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome2 = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        txtTaxa = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        txtQuantidade1 = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblNome3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblId1 = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        lblAtivo = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        cbxAtivo = new javax.swing.JComboBox<>();
        txtNomeProd = new javax.swing.JTextField();

        lblNome2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNome2.setText("Preço");

        lblNome1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNome1.setText("Quantidade");

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNome.setText("Nome");

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSalvar.setText("salvar");
        btnSalvar.setToolTipText("salvar os dados");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtTaxa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCancelar.setText("cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtQuantidade1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lblId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblId.setText("Id");

        lblNome3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNome3.setText("Taxa");

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        lblId1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblId1.setText("Categoria");

        cbxCategoria.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblAtivo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAtivo.setText("Ativo");

        txtPreco.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        cbxAtivo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cbxAtivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        cbxAtivo.setSelectedIndex(1);

        txtNomeProd.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalvar)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblId)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNome)
                                        .addComponent(txtNomeProd)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblId1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbxAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblAtivo))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(46, 46, 46)
                                                    .addComponent(lblNome1))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtQuantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGap(104, 104, 104)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNome2)
                                        .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNome3)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(56, 56, 56))
                    .addComponent(txtNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId1)
                    .addComponent(lblNome2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome1)
                            .addComponent(lblNome3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtQuantidade1))
                    .addComponent(txtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        //Recuperar as informações da UI
        Produto obj = new Produto();
        obj.setNome(txtNomeProd.getText());

        //Retornar a Categoria selecionada no ComboBox
        Categoria cat = (Categoria)cbxCategoria.getSelectedItem();
        obj.setId_categoria(cat.getId());

        obj.setNome(txtNomeProd.getText());
        obj.setPreco(Double.parseDouble(txtPreco.getText()));
        obj.setQntd(Integer.parseInt(txtQuantidade1.getText()));
        obj.setTaxa(Double.parseDouble(txtTaxa.getText()));
        obj.setFg_ativo(cbxAtivo.getSelectedIndex());

        //Executar a operação
        ProdutoDAO dao = new ProdutoDAO();
        int resultado;

        //se o campo Id estiver vazio
        if (txtId.getText().isEmpty()){
            //inserir
            resultado = dao.inserir(obj);
        }else{
            //atualizar
            obj.setId(Integer.parseInt(txtId.getText()));
            resultado = dao.atualizar(obj);
        }

        if (resultado >= 1){
            JOptionPane.showMessageDialog(
                null,
                "Operação realizada com sucesso!"
            );
        }else{
            JOptionPane.showMessageDialog(
                null,
                "Ocorreu um erro.",
                "Loja",
                JOptionPane.ERROR_MESSAGE
            );
        }
        this.dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxAtivo;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAtivo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblNome3;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNomeProd;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuantidade1;
    private javax.swing.JTextField txtTaxa;
    // End of variables declaration//GEN-END:variables
  private void preencherComboCategoria(){
        //recuperar a lista de categorias
        List<Categoria> lista = new CategoriaDAO().listar();
        
        if (lista != null){
            DefaultComboBoxModel m = new DefaultComboBoxModel();
            for(Categoria obj : lista){
                m.addElement(obj); //{id,nome,fg_ativo}
            }
            cbxCategoria.setModel(m);
        }
    }
}
