/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CategoriaDAO;
import controller.ClienteDAO;
import controller.ProdutoDAO;
import controller.TelefoneDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Produto;

/**
 *
 * @author ycar2
 */
public class FormaPesquisaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormaCadastrarCliente
     */
    public FormaPesquisaCliente() {
        initComponents();
        configurarForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabDadosClien = new javax.swing.JTable();

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNome.setText("Pesquisa por nome");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeKeyReleased(evt);
            }
        });

        tabDadosClien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabDadosClien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabDadosClienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabDadosClien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNome))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyReleased

        //if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            //recuperar o nome utilizado na pesquisa
            String nome = txtNome.getText();

            if (nome.isEmpty()){
                //exibir todos os registros da tabela
                preencherTabela(new ClienteDAO().listar());
            }else{
                //pesquisar pelo nome
                preencherTabela(
                    new ClienteDAO().pesquisarPorNome(nome)
                );
            }
            //}
    }//GEN-LAST:event_txtNomeKeyReleased

    private void tabDadosClienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabDadosClienMouseClicked

        //verificar se o usuário clicou 2x
        if (evt.getClickCount() == 2){

            //recuperar o ID da categoria selecionada
            int linha = tabDadosClien.getSelectedRow();
            String id = tabDadosClien.getValueAt(linha, 0).toString();

            //abrir o formulário de Produto e centralizar na tela
            FormCadastrarProduto f = new FormCadastrarProduto(id);
            Dimension d = this.getDesktopPane().getSize();
            this.getDesktopPane().add(f);
            f.setLocation( (d.width-f.getSize().width)/2, (d.height-f.getSize().height)/2);
            f.setVisible(true);

            //fechar o formulário de pesquisa
            this.dispose();
        }
    }//GEN-LAST:event_tabDadosClienMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tabDadosClien;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    private void configurarForm() {
        this.setTitle("Pesquisa de Produto");
        this.setResizable(false);
        this.setClosable(true);
        configurarTabela();
        
        preencherTabela(new ClienteDAO().listar());
        
    }

    private void configurarTabela() {
        DefaultTableModel m = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        m.addColumn("Id");
        m.addColumn("Nome");
        m.addColumn("CPF");
        m.addColumn("DDD");
        m.addColumn("Numero");
        m.addColumn("Ativo");
        tabDadosClien.setModel(m);
    }

    private void preencherTabela(List<Cliente> lista) {

        if (lista != null) {
            if (lista.size() > 0) {
                configurarTabela();
                DefaultTableModel m = (DefaultTableModel)tabDadosClien.getModel();
                for(Cliente obj : lista){
                    m.addRow(new Object[]
                        {
                            obj.getId(),
                            obj.getNome(),
                             //exibir o nome da Categoria
                            new TelefoneDAO().pesquisarPorId(
                                Integer.toString(obj.getId())
                            ),
                            obj.getFg_ativo() == 0 ? "Não" : "Sim"
                        }
                    );
                }
                tabDadosClien.setModel(m);
            } else {
                configurarTabela();
                JOptionPane.showMessageDialog(null, "A tabela não contém dados.", "Produto",
                        JOptionPane.INFORMATION_MESSAGE
                );
            }
        } else {
            JOptionPane.showMessageDialog(null,"Ocorreu um erro.","Produto",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
}
