/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author 834398
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        areaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCategoria = new javax.swing.JMenu();
        menuCadastroCategoria = new javax.swing.JMenuItem();
        menuCategoriaPesquisar = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenu();
        menuCadastroProduto = new javax.swing.JMenuItem();
        menuPesquisaProduto = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        menuCaadastroCliente = new javax.swing.JMenuItem();
        menuPesquisaCliente = new javax.swing.JMenuItem();
        menuCombustiveis = new javax.swing.JMenu();
        menuCadastrarCombustiveis = new javax.swing.JMenuItem();
        menuPesquisaCombustiveis = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuCategoria.setText("Categoria");

        menuCadastroCategoria.setText("Cadastrar");
        menuCadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroCategoriaActionPerformed(evt);
            }
        });
        menuCategoria.add(menuCadastroCategoria);

        menuCategoriaPesquisar.setText("Pesquisar");
        menuCategoriaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriaPesquisarActionPerformed(evt);
            }
        });
        menuCategoria.add(menuCategoriaPesquisar);

        jMenuBar1.add(menuCategoria);

        menuProduto.setText("Produto");

        menuCadastroProduto.setText("Cadastrar");
        menuCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroProdutoActionPerformed(evt);
            }
        });
        menuProduto.add(menuCadastroProduto);

        menuPesquisaProduto.setText("Visualizar");
        menuPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisaProdutoActionPerformed(evt);
            }
        });
        menuProduto.add(menuPesquisaProduto);

        jMenuBar1.add(menuProduto);

        menuCliente.setText("Cliente");

        menuCaadastroCliente.setText("Cadastrar");
        menuCaadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCaadastroClienteActionPerformed(evt);
            }
        });
        menuCliente.add(menuCaadastroCliente);

        menuPesquisaCliente.setText("Visualizar");
        menuPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisaClienteActionPerformed(evt);
            }
        });
        menuCliente.add(menuPesquisaCliente);

        jMenuBar1.add(menuCliente);

        menuCombustiveis.setText("Combustiveis");

        menuCadastrarCombustiveis.setText("Cadastrar");
        menuCombustiveis.add(menuCadastrarCombustiveis);

        menuPesquisaCombustiveis.setText("Pesquisar");
        menuCombustiveis.add(menuPesquisaCombustiveis);

        jMenuBar1.add(menuCombustiveis);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroCategoriaActionPerformed
        // TODO add your handling code here:
               abrirForm(new FormCategoriaCadastro());
    }//GEN-LAST:event_menuCadastroCategoriaActionPerformed

    private void menuPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisaProdutoActionPerformed
        abrirForm(new FormPesquisaProduto());
    }//GEN-LAST:event_menuPesquisaProdutoActionPerformed

    private void menuPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisaClienteActionPerformed
        abrirForm(new FormaPesquisaCliente());
    }//GEN-LAST:event_menuPesquisaClienteActionPerformed

    private void menuCaadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCaadastroClienteActionPerformed
        abrirForm(new FormCadastroCliente());
    }//GEN-LAST:event_menuCaadastroClienteActionPerformed

    private void menuCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroProdutoActionPerformed
        abrirForm(new FormCadastrarProduto());
    }//GEN-LAST:event_menuCadastroProdutoActionPerformed

    private void menuCategoriaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriaPesquisarActionPerformed
        abrirForm(new FormPesquisaCategoria());
    }//GEN-LAST:event_menuCategoriaPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuCaadastroCliente;
    private javax.swing.JMenuItem menuCadastrarCombustiveis;
    private javax.swing.JMenuItem menuCadastroCategoria;
    private javax.swing.JMenuItem menuCadastroProduto;
    private javax.swing.JMenu menuCategoria;
    private javax.swing.JMenuItem menuCategoriaPesquisar;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuCombustiveis;
    private javax.swing.JMenuItem menuPesquisaCliente;
    private javax.swing.JMenuItem menuPesquisaCombustiveis;
    private javax.swing.JMenuItem menuPesquisaProduto;
    private javax.swing.JMenu menuProduto;
    // End of variables declaration//GEN-END:variables

private void abrirForm(JInternalFrame f){
        if (areaTrabalho.getAllFrames().length == 0){
            Dimension d = areaTrabalho.getSize();
            areaTrabalho.add(f);
            f.setLocation( (d.width-f.getSize().width)/2,
                           (d.height-f.getSize().height)/2);
            f.setVisible(true);
        }
    }

}
